### ISSUE TITLE
Reloading plugin

### ISSUE THREAD

**Issue by stoivo** [skuroda/Sublime-AdvancedNewFile#128]
Hi am am having some trouble with this plugin when i am calling
sublime.sublime_api.plugin_host_ready()

Can you see if you can fix it? thx
I am using a MAC 10.10.3 and sublime 3 Build 3083

**Comment by skuroda** [comment]
Can you give me the error you are receiving? Also, can you let me know what plugin_host_ready() does? I don't see it in the docs, though I've been away from plugin development for a while now so not sure what new things have been added.

**Comment by stoivo** [comment]
I am sorry or happy. I cloned the plugin and  now I can't reproduce it. 
plugin_host_ready() is a function that does not have documentation, but it reloads all plugins.

**Comment by skuroda** [comment]
No problem, the error you were seeing was likely due to the super class of some of the commands. While they are set up properly, on reload, it occasionally breaks. I haven't looked into creating a more permanent fix for this, but I think I know what error you hit.
