### ISSUE TITLE
Traceback after 1.7 Update

### ISSUE THREAD

**Issue by MichalPodeszwa** [skuroda/Sublime-AdvancedNewFile#133]
I'm getting this traceback after having the plugin updated to the new version

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 141, in create_window_commands
    cmds.append(class_(window))
  File "advanced_new_file.commands.copy_file_command in /home/vessel/.config/sublime-text-3/Installed Packages/AdvancedNewFile.sublime-package", line 11, in __init__
TypeError: super(type, obj): obj must be an instance or subtype of type
```

Sublime 3 Build 3083
Ubuntu 15.04

After I added ANF to Ignored Packages, everything works fine.

**Comment by skuroda** [comment]
Can you try restarting Sublime Text. That happens from time to time due to how ST loads plugins, along with how I've structured the inheritance of the plugin. I haven't had a chance to dig through fixing it completely.

**Comment by MichalPodeszwa** [comment]
Oh, yeah. It works. Thanks

**Comment by skuroda** [comment]
No problem. I'm trying to catch up on the handful of bugs/requests I have, so I'll see if I can solve this. Thanks for using AdvancedNewFile.
