### ISSUE TITLE
Is there support for just creating a new directory?

### ISSUE THREAD

**Issue by tam5** [skuroda/Sublime-AdvancedNewFile#143]
I was wondering if there is support for a command which just creates a new directory. I know that if you create a new file and specify a file path that includes directories that do not yet exist, those directories are created. Thus it would seem much of the functionality already exists, but I have not found a way to create a directory by itself.

Does this feature already exist?

If not I can try to implement.

**Comment by skuroda** [comment]
If I recall correctly, it should create just the directory structure if you finish the path with `/` (e.g. `~/Desktop/mynewdir/` as the input string).

**Comment by tam5** [comment]
Ah yes thank you that is what I was looking for.
