### ISSUE TITLE
Command/Parameter to create file relative to the currently active view

### ISSUE THREAD

**Issue by FichteFoll** [skuroda/Sublime-AdvancedNewFile#144]
Often times I would like to quickly create a file next to the current file. You can provide an initial_dir parameter, but afaics (no real documentation on it) it does not expand any variables of some sort.

Previously I was using the "File: Duplicate" command from SIdeBarEnhancements, which required to adjust settings and file contents.

If this is already possible, then I apologize and would like to be referred to where this is documented. Thanks.

**Comment by skuroda** [comment]
Possible, but doesn't look like I documented it anywhere (woops). In any case, you should be able to reference the current file by using `:` as the first character in the path, or more comfortably `./`. Let me know if that works for you.

**Comment by FichteFoll** [comment]
Thank you, that works like a charm.
