### ISSUE TITLE
How to create files at specific paths by given type?

### ISSUE THREAD

**Issue by sarguvlad** [skuroda/Sublime-AdvancedNewFile#147]
Thank you for this amazingly time saving plugin.

Unfortunately I don't have a clear vision on how this can be achieved or which technique to use, but what I'm searching for is to run a command that will take as a first parameter the file type (not by extension) for example "lib" and the second one the file name "jquery.js" and the file to be created at "js/vendor/libs/jquery.js". I mean, firstly to configure the paths for every file type:

`{
	"lib": "js/vendor/libs/",
	"plugin": "js/vendor/plugins/"
}`

and then just give the file names.

Is this achievable using your awesome plugin?

Thank you

**Comment by skuroda** [comment]
Hi @sarguvlad, you can get something like that using aliases. Untested, but something like this should work (in the AdvancedNewFile settings file). 
```
{
    "alias": {
        "lib": "js/vendor/libs/"
    },
    "alias_root": "project_folder"
}
```

Then in the input, enter `lib:jquery.js`

**Comment by sarguvlad** [comment]
Wonderful, thank you for your instant reply, works like a charm!
