### ISSUE TITLE
Input only half visible

### ISSUE THREAD

**Issue by richstandbrook** [skuroda/Sublime-AdvancedNewFile#162]
Has anyone else had this? The input for a new file is half off the bottom of the window. I thought the statusbar was in the way, but even with it hidden the input is still only half visible.

![screen shot 2017-01-06 at 11 31 56](https://cloud.githubusercontent.com/assets/870611/21716769/76ec9320-d404-11e6-9eaa-d9d33f32dbbe.png)

**Comment by skuroda** [comment]
Hmm I haven't seen it before. I'll take a look at the code, but I haven't changed anything recently. Is it just this plugin that has that issue? It might be worth asking on the ST forum - https://forum.sublimetext.com/

**Comment by richstandbrook** [comment]
Only noticed on this one. Can you suggest another plugin that would have a bar at the bottom so I can check?

**Comment by skuroda** [comment]
Hmm, you can try https://packagecontrol.io/packages/File%20Rename.

**Comment by richstandbrook** [comment]
Yeah looks like it happens with that one too. I'll try disabling everything and turn AdvancedNewFile on.

**Comment by richstandbrook** [comment]
Ok. Nothing to do with other packages then. But looks like my changes to `line_padding_bottom`, `line_padding_top`, `caret_extra_bottom`, `caret_extra_top` and `font_size` to add more space is what's pushing it down. Would be great if you could find a way to accommodate this!

**Comment by skuroda** [comment]
Hmm we may want to create a ticket for the Sublime Text developers (https://forum.sublimetext.com/c/technical-support). Unfortunately I don't know that I can do anything from a plugin perspective.

**Comment by richstandbrook** [comment]
Cool, thanks @skuroda I'll do that. Actually happens with Sublimes find and replace as well.
