### ISSUE TITLE
file_templates how to use

### ISSUE THREAD

**Issue by dann1** [skuroda/Sublime-AdvancedNewFile#165]
Hello I'm trying to automatically add bangs, ex. !/usr/bin/python for new created .py files, and seems file_templates is the setting item for this, however, I really don't understand how to use it.

**Comment by skuroda** [comment]
Apologies I should have written better documentation. In your AdvancedNewFile user preferences you should create an entry like
```
[
    "file_templates": {
        "py": "!/usr/bin/python\n"
    }
]
```

**Comment by dann1** [comment]
thanks a lot now I'll be faster :+1: . I used a snippet but this is far better
