### ISSUE TITLE
A lot of problems

### ISSUE THREAD

**Issue by mikenils** [skuroda/Sublime-AdvancedNewFile#166]
Hi! Thank you very much for this plugin, I think it really cool, because there are around 700 stars and 81 forks. But, my personal user experience with it not very good.

There are a lot of problems in my case.... Everywhere. Here they are:

1. Default file extension doesn't work for me. That's what I have currently:

```
{
	"default_extension": "txt"
}
```

I also tried `"default_extension": ".txt"` (with dot before txt) but still doesn't work.

2. `"use_cursor_text": true` doesn't work if there are no text in first line. Also, I think it should take the text beside my cursor as file name. But instead of it, it always try to take the first line of the file, no matter where my cursor is currently located.

3. Just noticed now, new strange problem. Currently I have blank user preference file, but it still takes first line of file as file name.

4. Default path also doesn't work.

I use Sublime Text ver. 3, build 3126, on Windows 7 32 bit. I have no problems with any of another extensions, they are all work like a charm. (When I tested AdvancedNewFile, I disabled all of them).

It will be a good thing, I think, to post somewhere on the top of README.md completely workable user preferences preset.

**Comment by skuroda** [comment]
Hi @mikenils, when you run the command with any of the settings, are there any errors in the sublime text console?
