### ISSUE TITLE
Can not get aliases working

### ISSUE THREAD

**Issue by printercu** [skuroda/Sublime-AdvancedNewFile#173]
Hi, and thanks for great plugin!

Can you please help me with setting it up? I've got following config:

```json
{
  "default_root": "current",
  "aliases": {
    "r": "./"
  },
  "alias_root": "project_folder"
}
```

Assuming I have project at `/path/to/project` and open file `/path/to/project/config/database.yml`. When I create `test1` with ANF, it's placed into `/path/to/project/config/test1` - it's OK. And when I create `r:test2` with ANF, it's placed into `/path/to/project/config/r:test1`. What should I do to make `test2` be created in `/path/to/project` instead?

Is it also possible to have empty alias like `"aliases": {"": "./"}` to create files in project folder with `:filename`?

**Comment by skuroda** [comment]
Regarding the aliases not working, are there any errors in the ST console?

Regarding the empty alias, it's a special alias. Assuming the above are your ANF settings, specifying `:` should place you in the current directory of the file you are working on.

**Comment by printercu** [comment]
I had `aliases` instead of `alias`. So silly :) I've changed and now it works. 

`"alias": {"": "./"}`  does not allow to create file in project's root (ex. `:.gitignore`). As you said it is resolved to current dir. But because I have `"default_root": "current"` it just ignores leading colon.

**Comment by skuroda** [comment]
Ah, the `default_root` applies to the root when there is no text there. Perhaps an alternative would be to set the `default_root` to `project_folder`, then use `:` for the current directory.

**Comment by printercu** [comment]
OK, thanks!
