### ISSUE TITLE
AdvancedNewFile is not working.

### ISSUE THREAD

**Issue by lalitmee** [skuroda/Sublime-AdvancedNewFile#174]
I have Linux 16.04 and Sublime Text 3 Version: Build 3143. 
I am facing a problem with plugin AdvancedNewFile. I don't know whats going on. I uninstalled this package once and then reinstalled it. Still, it is not working.

**Please Help me. Thanks**

**Comment by skuroda** [comment]
Are there any errors in the Sublime Text console?

**Comment by lalitmee** [comment]
@skuroda Actually I installed sublime again. And now it's working. Thanx for replying.
