### ISSUE TITLE
Where can I find package file on my linux pc ?

### ISSUE THREAD

**Issue by vaxilicaihouxian** [skuroda/Sublime-AdvancedNewFile#175]
I know that I can browse the package folder with button 'Browse Packages..' on the top menu.
But I can not see this package's folder.
So,where can I find package file on my linux pc?

**Comment by vaxilicaihouxian** [comment]
I found that a zip file in my "Installed Packages" folder.Is that the package source files?

**Comment by skuroda** [comment]
Yes, in ST3, all the packages are (by default) zipped and installed in that folder. I haven't touched this plugin in a while, but you can check out https://github.com/skuroda/PackageResourceViewer to view the source files without needing to manually extract them. It'll traverse both `Packages` as well as `Installed Packages`

**Comment by vaxilicaihouxian** [comment]
Right,I read some documents for st package and I knew that the files in  `Packages` folder will replace the source files which is in the `Installed Packages` .
Thanks for your reply.
