### ISSUE TITLE
folder_exclude_patterns ignored

### ISSUE THREAD

**Issue by schmurfy** [skuroda/Sublime-AdvancedNewFile#181]
I like this plugin but is it possible to ignore some files/folders ?
I am currently working on a few javascript projects and node_modules is parsed resulting in the popup showing after a few seconds, when creating many files this is really annoying :(

**Comment by schmurfy** [comment]
seriously, am I the only one to be bothered by this ?

**Comment by skuroda** [comment]
Hi, which pop up are you referring to? I don't do much around this plug in
anymore but can take a look to see of it can be implement quickly.

**Comment by schmurfy** [comment]
Hi, I had another look around after posting and finally switch ed to Quick File Creator which has an exlude folder options.

My issue was that inside a javascript project with a node_modules when you use the shortcut to create a new file/folder there is a 4 seconds freeze which is damn annoying.
